---
openapi: 3.0.0
info:
  title: 接口文档
  description: 接口文档
  version: 4.0.0
paths:
  /pmpp/v4/open-api/material-module/organizations/{orgId}/userAuthorizations:
    get:
      tags: []
      description: userAuthorization
      operationId: 5083182c-2a81-4eaa-b4d9-f214f0b0a872
      parameters:
      - name: orgId
        in: path
        description: orgId
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: 成功时候的返回结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userMaterialAuthorizationResponseDTO'
  /v4/open-api/material-module/organizations/{orgId}/userAuthorizations:
    get:
      tags: []
      description: userAuthorization
      operationId: 2b2d6612-9f19-42ea-9793-c5e7d0b1c477
      parameters:
      - name: orgId
        in: path
        description: orgId
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: 成功时候的返回结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userMaterialAuthorizationResponseDTO'
components:
  schemas:
    userMaterialAuthorizationResponseDTO:
      required:
      - organizationLevel
      - tenantLevel
      type: object
      properties:
        organizationLevel:
          $ref: '#/components/schemas/userMaterialAuthorizationItem'
        tenantLevel:
          $ref: '#/components/schemas/userMaterialAuthorizationItem'
    userMaterialAuthorizationItem:
      required:
      - isAvailable
      - reason
      type: object
      properties:
        isAvailable:
          description: 是否可用
          type: boolean
        reason:
          description: 不可用的原因
          type: string
