---
openapi: 3.0.0
info:
  title: 接口文档
  description: 接口文档
  version: 4.0.0
paths:
  /pmpp/material-dictionary/v4/material-groups/list:
    get:
      tags: []
      description: com.glodon.cloudt.annotation.mark.OpenApi
      operationId: dde59a04-5db7-42d1-9226-359dd2d4a506
      parameters:
      - name: keywords
        in: query
        description: 关键字
        required: false
        schema:
          type: string
      - name: withExtendInfo
        in: query
        description: 是否包偏差信息，默认false
        required: true
        schema:
          type: boolean
      - name: varietyCode
        in: query
        description: 类型编码
        required: false
        schema:
          type: string
      - name: sortField
        in: query
        description: 排序字段
        required: false
        schema:
          type: string
      - name: ascend
        in: query
        description: 升序还是降序
        required: false
        schema:
          type: boolean
      responses:
        "200":
          description: 成功时候的返回结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jsonResult_list_materialGroupDTO'
  /v4/material-groups/list:
    get:
      tags: []
      description: com.glodon.cloudt.annotation.mark.OpenApi
      operationId: a9430263-bdd7-46a8-83bc-8184182b5d0b
      parameters:
      - name: keywords
        in: query
        description: 关键字
        required: false
        schema:
          type: string
      - name: withExtendInfo
        in: query
        description: 是否包偏差信息，默认false
        required: true
        schema:
          type: boolean
      - name: varietyCode
        in: query
        description: 类型编码
        required: false
        schema:
          type: string
      - name: sortField
        in: query
        description: 排序字段
        required: false
        schema:
          type: string
      - name: ascend
        in: query
        description: 升序还是降序
        required: false
        schema:
          type: boolean
      responses:
        "200":
          description: 成功时候的返回结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jsonResult_list_materialGroupDTO'
components:
  schemas:
    jsonResult_list_materialGroupDTO:
      required:
      - code
      - message
      - data
      - throwable
      type: object
      properties:
        code:
          description: 响应码
          type: integer
        message:
          description: 响应消息
          type: string
        data:
          description: 响应数据
          type: array
          items:
            $ref: '#/components/schemas/materialGroupDTO'
        throwable:
          description: 响应异常
          type: object
    materialGroupDTO:
      required:
      - id
      - parentId
      - code
      - fullCode
      - name
      - remark
      - orderNo
      - delete
      - fullPath
      - tenantId
      - orgFullId
      - level
      - leafNode
      - children
      - dataSource
      - deviationId
      - deviationType
      - deviationPlus
      - deviationMinus
      - industryMaterialGroupId
      - materialCount
      - unitId
      - unitPid
      - trdMapped
      - category
      - standard
      - varietyCode
      - allowSubordinateManage
      - operation
      - orgId
      - id
      - deviationType
      - deviationPlus
      - deviationMinus
      - deviationInfo
      - weighTypeEnum
      - categoryId
      - materialId
      - isForceUpdate
      - parentNodeId
      - modified
      - success
      type: object
      properties:
        id:
          description: id 对应数据库表中的主键ID
          type: integer
        parentId:
          description: 父级id
          type: integer
        code:
          description: 编码
          type: string
        fullCode:
          description: 编码全路径
          type: string
        name:
          description: 名称
          type: string
        remark:
          description: 备注
          type: string
        orderNo:
          description: 排序
          type: integer
        delete:
          description: 是否删除
          type: boolean
        fullPath:
          description: 全路径
          type: string
        tenantId:
          description: 租户id
          type: integer
        orgFullId:
          description: 全组织id
          type: string
        level:
          description: 节点级别
          type: integer
        leafNode:
          description: 叶子节点
          type: boolean
        children:
          description: 子级
          type: array
          items:
            $ref: '#/components/schemas/materialGroupDTO'
        dataSource:
          description: 是否从企业级选择标识
          type: integer
        deviationId:
          description: 偏差ID
          type: integer
        deviationType:
          description: 偏差类型
          type: string
        deviationPlus:
          description: 正差
          type: number
        deviationMinus:
          description: 负差
          type: number
        industryMaterialGroupId:
          description: 工料机类别id
          type: integer
        materialCount:
          description: 材料总数
          type: integer
        unitId:
          description: 三方id
          type: string
        unitPid:
          description: 三方pid
          type: string
        trdMapped:
          description: 三方匹配状态
          type: boolean
        category:
          description: 1代表是品类
          type: integer
        standard:
          description: 是否标准类别
          type: boolean
        varietyCode:
          description: 类型编码
          type: string
        allowSubordinateManage:
          description: 是否允许下级维护
          type: boolean
        operation:
          $ref: '#/components/schemas/object'
        orgId:
          description: 机构id
          type: integer
        deviationInfo:
          $ref: '#/components/schemas/deviationInfoDTO'
        weighTypeEnum:
          $ref: '#/components/schemas/weighTypeEnum'
        categoryId:
          description: 类别id
          type: integer
        materialId:
          description: 材料id
          type: integer
        isForceUpdate:
          description: 是否强制修改
          type: boolean
        parentNodeId:
          description: 父id
          type: integer
        modified:
          description: 是否手动修改后1是0否
          type: boolean
        success:
          description: 是否同步成功
          type: boolean
    object:
      type: object
    deviationInfoDTO:
      required:
      - deviationType
      - deviationPlus
      - deviationMinus
      type: object
      properties:
        deviationType:
          description: 偏差类型
          type: string
        deviationPlus:
          description: 正差
          type: number
        deviationMinus:
          description: 负差
          type: number
    weighTypeEnum:
      required:
      - desc
      - name
      - ordinal
      type: object
      properties:
        desc:
          description: desc
          type: string
        name:
          description: name
          type: string
        ordinal:
          description: ordinal
          type: integer
